### ISSUE TITLE
Please add linux support

### ISSUE THREAD

**Issue by gabek** [rnelson/fontsploder#1]

**Comment by rnelson** [comment]
When either Pafford or I run Linux, I'll consider it.

**Comment by gabek** [comment]
I thought maybe I could make the change myself but I can't get it to build.  
![screen shot 2015-04-17 at 1 37 06 pm](https://cloud.githubusercontent.com/assets/414923/7210481/fb2ce4a8-e506-11e4-9e0d-5289ebf3b843.png)

**Comment by rnelson** [comment]
Haha, yeah. Also, there's no GDI, which is what it's using to add/remove fonts.

**Comment by gabek** [comment]
I'll try it on my BeOS box instead.  Thanks for your help.

**Comment by rnelson** [comment]
I tried to use Haiku on a machine, but their wifi drivers are from FreeBSD 9.3, and the chip in the machine only works on Windows and Linux. :'(
